
'use server';
/**
 * @fileOverview An AI flow for analyzing financial performance data.
 *
 * - analyzePerformance - A function that takes financial data and returns an AI-generated analysis.
 * - PerformanceAnalysisInput - The input type for the analysis flow.
 * - PerformanceAnalysisOutput - The return type for the analysis flow.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PerformanceAnalysisInputSchema = z.object({
  periodLabel: z.string().describe('The label for the period being analyzed (e.g., "Últimos 28 días").'),
  totalRevenue: z.number().describe('Total gross revenue for the period.'),
  totalVariableExpenses: z.number().describe('Total variable expenses for the period.'),
  netProfit: z.number().describe('Final net profit for the period.'),
  netMemberShare: z.number().describe('Net share amount for each member.'),
  topPerformingGroup: z.object({
    name: z.string().describe('Name of the top-performing group.'),
    total: z.number().describe('Revenue generated by the top group.'),
  }),
  topPerformingLocation: z.object({
    name: z.string().describe('Name of the top-performing location.'),
    total: z.number().describe('Revenue generated by the top location.'),
  }),
  expenseCategories: z.array(z.object({
      name: z.string().describe('Category name.'),
      value: z.number().describe('Total amount for the category.')
  })).describe('Breakdown of expenses by category.'),
  historicalData: z.string().optional().describe('A comma-separated string of historical monthly revenue data in the format "Period:Value,Period:Value,...".')
});
export type PerformanceAnalysisInput = z.infer<typeof PerformanceAnalysisInputSchema>;

const PerformanceAnalysisOutputSchema = z.object({
  title: z.string().describe("Un título llamativo y corto para el análisis, en español."),
  summary: z.string().describe("Un resumen de 1-2 frases del estado financiero general del período, en español."),
  positivePoints: z.array(z.string()).describe("Una lista de 2 a 3 puntos positivos o éxitos clave del período, en español. Cada punto debe ser una frase corta y directa."),
  areasForImprovement: z.array(z.string()).describe("Una lista de 2 a 3 áreas de mejora, riesgos o puntos de atención, en español. Cada punto debe ser una frase corta y directa."),
  recommendation: z.string().describe("Una recomendación principal o siguiente paso sugerido, basado en el análisis. Debe ser una o dos frases, en español."),
});
export type PerformanceAnalysisOutput = z.infer<typeof PerformanceAnalysisOutputSchema>;

const prompt = ai.definePrompt({
    name: 'analyzePerformancePrompt',
    input: { schema: PerformanceAnalysisInputSchema },
    output: { schema: PerformanceAnalysisOutputSchema },
    prompt: `
        Eres un asesor financiero experto para un negocio de alquiler de scooters. Tu tarea es analizar el rendimiento del período y presentar un informe claro, conciso y accionable en español.

        Aquí están los datos para el período '{{periodLabel}}':
        - Ingresos Brutos Totales: {{totalRevenue}}
        - Gastos Variables Totales: {{totalVariableExpenses}}
        - Beneficio Neto Final: {{netProfit}}
        - Cuota Neta por Miembro: {{netMemberShare}}
        - Grupo con Mayor Rendimiento: {{topPerformingGroup.name}} ({{topPerformingGroup.total}})
        - Ubicación con Mayor Rendimiento: {{topPerformingLocation.name}} ({{topPerformingLocation.total}})

        Desglose de gastos:
        {{#each expenseCategories}}
        - {{name}}: {{value}}
        {{/each}}
        
        {{#if historicalData}}
        Datos históricos de ingresos para contexto de tendencia: {{historicalData}}
        {{/if}}

        Basado en estos datos, genera el siguiente análisis:
        1.  **Título:** Un título corto y potente que resuma el período.
        2.  **Resumen:** Una o dos frases que describan la salud financiera general. Menciona si fue un buen o mal período.
        3.  **Puntos Positivos:** Identifica 2-3 éxitos claros. ¿Qué funcionó bien? ¿Qué grupo o ubicación destacó?
        4.  **Áreas de Mejora:** Identifica 2-3 riesgos o problemas. ¿Qué gastos son preocupantes? ¿Hay alguna tendencia negativa?
        5.  **Recomendación:** Ofrece una sugerencia principal y concreta. ¿Qué debería hacer el negocio a continuación?

        Sé directo, usa un lenguaje de negocios pero fácil de entender. No repitas los números exactos a menos que sea para enfatizar un punto crítico. Enfócate en las conclusiones.
    `,
});

const analyzePerformanceFlow = ai.defineFlow(
  {
    name: 'analyzePerformanceFlow',
    inputSchema: PerformanceAnalysisInputSchema,
    outputSchema: PerformanceAnalysisOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    if (!output) {
      throw new Error("AI analysis failed to generate a valid output.");
    }
    return output;
  }
);

export async function analyzePerformance(input: PerformanceAnalysisInput): Promise<PerformanceAnalysisOutput> {
    return analyzePerformanceFlow(input);
}
